### ISSUE TITLE
undefined method `val' for #<Arel::Nodes::BindParam:0x007fe86e7a83d0>

### ISSUE THREAD

**Issue by xdougx** [rails/arel#357]
Im having also a probleman like this, ive saw a issue like this, but even updating my gem this error persist
```
NoMethodError: undefined method `val' for #<Arel::Nodes::BindParam:0x007fe86e7a83d0>
	from /Users/douglas/.rvm/gems/ruby-2.1.0/gems/activerecord-4.2.0/lib/active_record/relation.rb:572:in `block (2 levels) in where_values_hash'
	from /Users/douglas/.rvm/gems/ruby-2.1.0/gems/activerecord-4.2.0/lib/active_record/relation.rb:568:in `fetch'
	from /Users/douglas/.rvm/gems/ruby-2.1.0/gems/activerecord-4.2.0/lib/active_record/relation.rb:568:in `block in where_values_hash'
	from /Users/douglas/.rvm/gems/ruby-2.1.0/gems/activerecord-4.2.0/lib/active_record/relation.rb:566:in `map'
	from /Users/douglas/.rvm/gems/ruby-2.1.0/gems/activerecord-4.2.0/lib/active_record/relation.rb:566:in `where_values_hash'
	from /Users/douglas/.rvm/gems/ruby-2.1.0/gems/activerecord-4.2.0/lib/active_record/relation.rb:579:in `scope_for_create'
	from /Users/douglas/.rvm/gems/ruby-2.1.0/gems/activerecord-4.2.0/lib/active_record/associations/singular_association.rb:38:in `create_scope'
	from /Users/douglas/.rvm/gems/ruby-2.1.0/gems/activerecord-4.2.0/lib/active_record/associations/association.rb:168:in `initialize_attributes'
	from /Users/douglas/.rvm/gems/ruby-2.1.0/gems/activerecord-4.2.0/lib/active_record/associations/association.rb:248:in `block in build_record'
	from /Users/douglas/.rvm/gems/ruby-2.1.0/gems/activerecord-4.2.0/lib/active_record/core.rb:282:in `initialize'
	from /Users/douglas/.rvm/gems/ruby-2.1.0/gems/activerecord-4.2.0/lib/active_record/inheritance.rb:61:in `new'
	from /Users/douglas/.rvm/gems/ruby-2.1.0/gems/activerecord-4.2.0/lib/active_record/inheritance.rb:61:in `new'
	from /Users/douglas/.rvm/gems/ruby-2.1.0/gems/activerecord-4.2.0/lib/active_record/reflection.rb:131:in `build_association'
	from /Users/douglas/.rvm/gems/ruby-2.1.0/gems/activerecord-4.2.0/lib/active_record/associations/association.rb:247:in `build_record'
	from /Users/douglas/.rvm/gems/ruby-2.1.0/gems/activerecord-4.2.0/lib/active_record/associations/singular_association.rb:29:in `build'
	from /Users/douglas/.rvm/gems/ruby-2.1.0/gems/activerecord-4.2.0/lib/active_record/associations/builder/singular_association.rb:18:in `build_address'
... 14 levels...
	from /Users/douglas/.rvm/gems/ruby-2.1.0/gems/railties-4.2.0/lib/rails/commands/console.rb:9:in `start'
	from /Users/douglas/.rvm/gems/ruby-2.1.0/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:68:in `console'
	from /Users/douglas/.rvm/gems/ruby-2.1.0/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /Users/douglas/.rvm/gems/ruby-2.1.0/gems/railties-4.2.0/lib/rails/commands.rb:17:in `<top (required)>'
	from /Users/douglas/.rvm/gems/ruby-2.1.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `require'
	from /Users/douglas/.rvm/gems/ruby-2.1.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `block in require'
	from /Users/douglas/.rvm/gems/ruby-2.1.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /Users/douglas/.rvm/gems/ruby-2.1.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `require'
	from /Users/douglas/workspace/kanamobi/api-kanamobi/bin/rails:8:in `<top (required)>'
	from /Users/douglas/.rvm/gems/ruby-2.1.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:268:in `load'
	from /Users/douglas/.rvm/gems/ruby-2.1.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:268:in `block in load'
	from /Users/douglas/.rvm/gems/ruby-2.1.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /Users/douglas/.rvm/gems/ruby-2.1.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:268:in `load'
	from /Users/douglas/.rvm/rubies/ruby-2.1.0/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/douglas/.rvm/rubies/ruby-2.1.0/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
```

classes:

```
class Company < ActiveRecord::Base
  # concerns
  include Addressible
  include Archivable
  include Buildable
  include Pageable
  include Jsonable


  # associations
  has_many :contacts
  has_one :address

  # validations
  validates :name, :status, presence: true

  accepts_nested_attributes_for :address, allow_destroy: true

end
```

```
class Address < ActiveRecord::Base
  # concerns
  include Buildable
  include Jsonable

  # associations
  belongs_to :addressible, polymorphic: true
  
  # validations  
  validates :line1, :state, :city, presence: true
  validates_format_of :zip, with: /\A[0-9]{5}-[0-9]{3}\z/


  def full_street_address
    "#{line1}, #{district}, #{city}, #{state}, #{zip}"
  end
end

```

**Comment by xdougx** [comment]
when i remove:
```
accepts_nested_attributes_for :address, allow_destroy: true
```
company has no errors.

**Comment by xdougx** [comment]
Please close this issue, i found the error, has_one address it was repeating in my concern

**Comment by eileencodes** [comment]
Thanks for reporting back @xdougx!
