### ISSUE TITLE
undefined method `visit_Arel_Nodes_Casted' for Arel::Visitors::Dot

### ISSUE THREAD

**Issue by dungdm93** [rails/arel#419]
I found some errors when I try visualize Arel AST with GraphViz:
```ruby
  it 'arel' do
    users = Arel::Table.new(:users)
    query = users.where(users[:id].eq(23))
    visualization query
  end

  def visualization(query)
    dot = query.to_dot           # error is raised here
    puts dot
    graph = GraphViz.parse_string(dot)
    graph.output(png: 'query.png')
  end
```
Stack Trace:
```
TypeError: Cannot visit Arel::Nodes::Casted
/arel-6.0.3/lib/arel/visitors/visitor.rb:35:in `rescue in visit'
/arel-6.0.3/lib/arel/visitors/visitor.rb:29:in `visit'
/arel-6.0.3/lib/arel/visitors/dot.rb:236:in `block in visit'
/arel-6.0.3/lib/arel/visitors/dot.rb:254:in `with_node'
/arel-6.0.3/lib/arel/visitors/dot.rb:235:in `visit'
....
------------------
--- Caused by: ---
NoMethodError:
  undefined method `visit_Arel_Nodes_Casted' for #<Arel::Visitors::Dot:0x00000006d8bb60>
  /arel-6.0.3/lib/arel/visitors/visitor.rb:29:in `visit'
```

**Comment by valasensio** [comment]
Me, too. 

> Exception `NoMethodError' at /usr/local/rvm/gems/ruby-2.0.0-p247/gems/arel-6.0.3/lib/arel/visitors/visitor.rb:29 - undefined method `visit_Arel_Nodes_Casted' for #<Arel::Visitors::DepthFirst:0x000000071cd660>
