### ISSUE TITLE
activerecord (5.1.4) lib/active_record/relation/predicate_builder.rb:113:in `new' not passing a value, causing Arel 9.0.0 to fail

### ISSUE THREAD

**Issue by ehatjissavvas** [rails/arel#508]
failing in :  'object=model.where(column: value)'  (in my case I have  'object=model.where(column: value).select(:column)' but the failure happened in the where clause)
with : 'wrong number of arguments (given 0, expected 1)'

The system runs on ruby 2.4.2 and Rails 5.1.4 and I recently updated Arel 8.0.0 to 9.0.0

StackTrace:

- arel (9.0.0) lib/arel/nodes/bind_param.rb:7:in `initialize'

- activerecord (5.1.4) lib/active_record/relation/predicate_builder.rb:113:in `new'

```ruby
if can_be_bound?(column_name, value)
              result[column_name] = Arel::Nodes::BindParam.new
              binds << build_bind_param(column_name, value)
end
```

**Comment by ehatjissavvas** [comment]
https://github.com/rails/rails/commit/213796fb4936dce1da2f0c097a054e1af5c25c2c#diff-2ec9993375ecb711e08452788d625581
The above commit in Rails (5.2.0) seems that it fixes that issue, it will come with Rails 5.2 but is confusing as 5.2.0 is not released yet
